### ISSUE TITLE
Hit ratio

### ISSUE THREAD

**Issue by BlackCurrantPrince** [chalianwar/docker-performance#1]
def update_layers(self, repo, size, timestmap):
        if repo in self.manifest:
            for layer in self.manifest[repo]:
                if size - 1000 < layer[2] and size + 1000 > layer[2]:  
                    self.hit += 1
                    layer[1] += 1                                      
        else:
            self.miss += 1   

In your code,It updates the timestamp by judging whether it is the same layer in self.manifest.So I can`t understand why we hit it when the layer has a range of values of 2000.

**Comment by chalianwar** [comment]
It is an additional check to make sure that size of layer is also within this range just to be certain. Though layer id of two layers should not be same but still this check was added to be sure.
